name: CI

on: push

jobs:
  js:
    name: Build JavaScript NPM Package
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Install Node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    
    - name: Install NPM Packages
      run: cd js && npm install

    - name: Lint
      run: cd js && npm run lint

    - name: Compile
      run: cd js && npm run build

    - name: Execute Jest unit tests for Node support
      run: cd js && npm run test:node

    - name: Execute Karma unit tests for browser support
      run: cd js && npm run test:browser

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: js/build/coverage/node/cobertura-coverage.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: commonlibs-js-${{ github.run_number }}
        path: |
          js/**
          !**/node_modules/**

    - name: Publish NPM Package
      if: github.ref == 'refs/heads/master'
      uses: JS-DevTools/npm-publish@v1
      with:
        package: js/package.json
        token: ${{ secrets.NPM_TOKEN }}

  dotnet:
    name: Build .NET Core NuGet Package
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}

    - name: Compile
      run: |
        cd dotnet/
        dotnet restore
        dotnet build -c Release

    - name: Run Unit Tests
      run: |
        cd dotnet/
        dotnet test UnitTests/LeoSingleton.CommonLibs.UnitTests.csproj --collect:"XPlat Code Coverage"

    - name: Publish Code Coverage
      uses: codecov/codecov-action@v1
      with:
        file: dotnet/UnitTests/TestResults/*/coverage.cobertura.xml

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: commonlibs-dotnet-${{ github.run_number }}
        path: |
          dotnet/**

    - name: Publish NuGet Package
      if: github.ref == 'refs/heads/master'
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: dotnet/CommonLibs/LeoSingleton.CommonLibs.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        TAG_FORMAT: dotnet-v*
        NUGET_KEY: ${{ secrets.NUGET_AUTH_TOKEN }}
        INCLUDE_SYMBOLS: true
